In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv('Dataku.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(x)

[['Ronald' 60.0 50.0]
 ['Aldo' 70.0 80.0]
 ['Kimoy' 85.0 80.0]
 ['Ronald' 80.0 90.0]
 ['Aldo' 60.0 75.0]
 ['Kimoy' nan 60.0]
 ['Ronald' 90.0 60.0]
 ['Aldo' 80.0 70.0]
 ['Kimoy' 65.0 nan]
 ['Ronald' 65.0 65.0]]


In [8]:
print(y)

['No;;' 'Yes;;' 'Yes;;' 'Yes;;' 'No;;' 'No;;' 'Yes;;' 'Yes;;' 'No;;'
 'No;;']


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [11]:
print(x)

[['Ronald' 60.0 50.0]
 ['Aldo' 70.0 80.0]
 ['Kimoy' 85.0 80.0]
 ['Ronald' 80.0 90.0]
 ['Aldo' 60.0 75.0]
 ['Kimoy' 72.77777777777777 60.0]
 ['Ronald' 90.0 60.0]
 ['Aldo' 80.0 70.0]
 ['Kimoy' 65.0 70.0]
 ['Ronald' 65.0 65.0]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[0.0 0.0 1.0 60.0 50.0]
 [1.0 0.0 0.0 70.0 80.0]
 [0.0 1.0 0.0 85.0 80.0]
 [0.0 0.0 1.0 80.0 90.0]
 [1.0 0.0 0.0 60.0 75.0]
 [0.0 1.0 0.0 72.77777777777777 60.0]
 [0.0 0.0 1.0 90.0 60.0]
 [1.0 0.0 0.0 80.0 70.0]
 [0.0 1.0 0.0 65.0 70.0]
 [0.0 0.0 1.0 65.0 65.0]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[0 1 1 1 0 0 1 1 0 0]


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

In [17]:
print(x_train)

[[0.0 0.0 1.0 90.0 60.0]
 [1.0 0.0 0.0 60.0 75.0]
 [0.0 0.0 1.0 60.0 50.0]
 [0.0 0.0 1.0 80.0 90.0]
 [1.0 0.0 0.0 70.0 80.0]
 [1.0 0.0 0.0 80.0 70.0]
 [0.0 1.0 0.0 65.0 70.0]
 [0.0 1.0 0.0 72.77777777777777 60.0]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 85.0 80.0]
 [0.0 0.0 1.0 65.0 65.0]]


In [19]:
print(y_train)

[1 0 0 1 1 1 0 0]


In [20]:
print(y_test)

[1 0]


In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [22]:
print(x_train)

[[0.0 0.0 1.0 1.7853707284853455 -0.7916697209538892]
 [1.0 0.0 0.0 -1.227442375833676 0.4750018325723335]
 [0.0 0.0 1.0 -1.227442375833676 -1.6361174233047044]
 [0.0 0.0 1.0 0.7810996937123383 1.7416733860985563]
 [1.0 0.0 0.0 -0.2231713410606689 0.8972256837477411]
 [1.0 0.0 0.0 0.7810996937123383 0.052777981396925945]
 [0.0 1.0 0.0 -0.7253068584471725 0.052777981396925945]
 [0.0 1.0 0.0 0.0557928352651658 -0.7916697209538892]]


In [23]:
print(x_test)

[[0.0 1.0 0.0 1.2832352110988419 0.8972256837477411]
 [0.0 0.0 1.0 -0.7253068584471725 -0.36944586977848165]]
